
# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

tagUrl : "http://localhost:9002/tags"
dbName : "morphia_user"
userName : "admin"
userPassword : "password"